command_timeout = 1800000

format = """
$directory\
[ ](fg:#343a40 bg:#ca6702)\
$nodejs\
[ ](fg:#ca6702 bg:#bb3e03)\
$ruby\
[ ](bg:#2b2b2b fg:#bb3e03)\
$fill\
[](#343a40)\
$kubernetes\
$line_break\
$git_branch\
$git_status\
[](fg:#1d3557) 
"""

right_format = """
$time
"""

[fill]
symbol = " "

[sudo]
style = "bg:#343a40 fg:#bb3e03"
format = '[ $symbol ]($style)'
symbol = ""
disabled = false

[character]
style = "bg: #1d3557"
success_symbol = "[](#023e8a)"
error_symbol = "[](#e63946)"
vicmd_symbol = "[](#b5179e)"


# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
style_user = "bg:#343a40 fg:#343a40 bold"
style_root = "bg:#005f73 bold"
format = '[ $user ]($style)'

[directory]
style = "bg:#343a40 fg:#e0fbfc"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#1d3557 fg:#f1faee"
format = '[[ $symbol]($style fg:#0096c7) $branch]($style)'

[git_status]
style = "bg:#1d3557"
ahead = " [[](bg:#1d3557 fg:#0096c7)$count](bg:#1d3557 fg:#f1faee)"
behind = " [[](bg:#1d3557 fg:#0096c7)$count](bg:#1d3557 fg:#f1faee)"
deleted = " [[﯊](bg:#1d3557 fg:#0096c7)$count](bg:#1d3557 fg:#f1faee)"
diverged = " [](bg:#1d3557 fg:#0096c7)"
stashed = " [[](bg:#1d3557 fg:#0096c7)$count](bg:#1d3557 fg:#f1faee)"
modified = " [[](bg:#1d3557 fg:#0096c7)$count](bg:#1d3557 fg:#f1faee)"
staged = " [[](bg:#1d3557 fg:#0096c7)$count](bg:#1d3557 fg:#f1faee)"
untracked = " [[](bg:#1d3557 fg:#0096c7)$count](bg:#1d3557 fg:#f1faee)"
format = '[($all_status$ahead_behind)](bg:#1d3557 fg:#f1faee)'

[nodejs]
symbol = ""
style = "bg:#ca6702 fg:#582f0e"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = ""
style = "bg:#bb3e03 fg:#370617"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol = "⎈"
style = "bg:#343a40 fg:#e0fbfc"
format = '[ $symbol  $context ]($style)'
disabled = false

[kubernetes.context_aliases]
"eks-st" = "staging"
"eks-pr" = "production"

[time]
disabled = false
style = "fg:#98c1d9"
time_format = "%F %T"
format = "[$time]($style)"
