format = """
$username\
$sudo\
[](bg:#ee9b00 fg:#343a40)\
$directory\
[](fg:#ee9b00 bg:#ca6702)\
$nodejs\
[](fg:#ca6702 bg:#bb3e03)\
$ruby\
[](fg:#bb3e03)\
$fill\
[](#343a40)\
$kubernetes\
$line_break\
$git_branch\
$git_status\
[](fg:#168aad) 
"""

right_format = """
$time
"""

[fill]
symbol = " "

[sudo]
style = "bg:#343a40 fg:#bb3e03"
format = '[ $symbol ]($style)'
symbol = ""
disabled = false

[character]
style = "bg: #168aad"
success_symbol = "[](#023e8a)"
error_symbol = "[](#e63946)"
vicmd_symbol = "[](#b5179e)"


# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
style_user = "bg:#343a40 fg:#6c757d bold"
style_root = "bg:#005f73 bold"
format = '[ $user ]($style)'

[directory]
style = "bg:#ee9b00 fg:#432818"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#168aad fg:#22333b"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:#168aad fg:#22333b"
ahead = " [](bg:#168aad fg:#126782)$count"
behind = " [](bg:#168aad fg:#126782)$count"
deleted = " [﯊](bg:#168aad fg:#126782)$count"
diverged = " [](bg:#168aad fg:#126782)"
stashed = " [](bg:#168aad fg:#126782)$count"
modified = " [](bg:#168aad fg:#126782)$count"
staged = " [](bg:#168aad fg:#126782)$count"
untracked = " [](bg:#168aad fg:#126782)$count"
format = '[($all_status$ahead_behind)]($style)'

[nodejs]
symbol = ""
style = "bg:#ca6702 fg:#582f0e"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = ""
style = "bg:#bb3e03 fg:#370617"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
symbol = "⎈"
style = "bg:#343a40 fg:#6c757d"
format = '[ $symbol  $context ]($style)'
disabled = false

[kubernetes.context_aliases]
"eks-st" = "staging"
"eks-pr" = "production"

[time]
disabled = false
style = "fg:#343a40"
time_format = "%F %T"
format = "[$time]($style)"
